In [1]:
import polars as pl
import pandas as pd
import seaborn as sb
import numpy as np
from pathlib import Path
from datetime import date

In [2]:
# Carregando os dados de penalidades aplicadas a operadoras com scan (LazyFrame - não materializa o DataFrame imediatamente)
lf_origem_penalidades_aplicadas_a_operadoras = pl.scan_parquet(r"c:\GIT\DadosANS\Cargas\processamentos\penalidades_20260511_213501\ingestao\downloads\penalidades_aplicadas_a_operadoras.parquet")

# collect_schema() é usado para obter o esquema do LazyFrame sem materializar os dados; 
# O método .columns() é mais custoso em recursos, pois pode exigir a leitura de uma amostra dos dados para inferir os tipos de coluna.
# O método .names() retorna apenas os nomes das colunas consultando o schema, o que é mais leve.
lf_origem_penalidades_aplicadas_a_operadoras.collect_schema().names()

['NR_DEMANDA',
 'NR_PROCESSO',
 'TIPO_PROCESSO',
 'OBJETO',
 'REGISTRO_OPERADORA',
 'CNPJ',
 'RAZAO_SOCIAL',
 'SITUACAO_OPERADORA',
 'STATUS_DEMANDA',
 'DT_DECISAO_1A',
 'DT_PUBLICACAO_1A',
 'DT_PUBLICACAO_1A_FINAL',
 'VL_MULTA_FIXA_1A',
 'VL_MULTA_DIARIA_1A',
 'VL_TOTAL_APLICADO_1A',
 'DT_CIENCIA_RECONSIDERA_TOTAL',
 'DT_DECISAO_2A',
 'DT_PUBLICACAO_2A',
 'TIPO_DECISAO_2A',
 'VL_MULTA_FIXA_2A',
 'VL_MULTA_DIARIA_2A',
 'VL_TOTAL_APLICADO_2A',
 'VL_MULTA_FINAL_APLICADA',
 'VL_TOTAL_DESCONTOS',
 'DT_ARQUIVAMENTO',
 'MOTIVO_ARQUIVAMENTO',
 'TIPO_PENALIDADE',
 'DT_SUSPENSAO_ADM',
 'DT_SUSPENSAO_JUD',
 'NR_GRU',
 'DT_VENC_GRU',
 'VL_GRU',
 'DE_SITUACAO_GRU',
 'DT_PAGTO_A_VISTA_ANS',
 'VL_PAGO_A_VISTA_ANS',
 'DT_VENC_1A_PARC_ANS',
 'VL_PARCELAS_ANS_PAGAS',
 'STATUS_PARCELAMENTO',
 'DT_INSCRICAO',
 'INSCRITO_DA',
 'ORIGEM_PAGAMENTO',
 'NR_COMPETENCIA_CARGA']

In [3]:
# Definição das colunas de possível interesse para a análise
colunas_desejaveis = [
    'NR_DEMANDA',
    'NR_PROCESSO',
    'TIPO_PROCESSO',
    'REGISTRO_OPERADORA',
    'STATUS_DEMANDA',
    'DT_PUBLICACAO_1A_FINAL',
    'VL_MULTA_FIXA_1A',
    'VL_TOTAL_APLICADO_1A',
    'DT_CIENCIA_RECONSIDERA_TOTAL',
    'TIPO_DECISAO_2A',
    'VL_MULTA_FIXA_2A',
    'VL_TOTAL_APLICADO_2A',
    'VL_MULTA_FINAL_APLICADA',
    'VL_TOTAL_DESCONTOS',
    'DT_ARQUIVAMENTO',
    'MOTIVO_ARQUIVAMENTO',
    'TIPO_PENALIDADE',
    'DT_SUSPENSAO_ADM',
    'DT_SUSPENSAO_JUD',
    'DT_VENC_GRU',
    'VL_GRU',
    'DE_SITUACAO_GRU',
    'DT_PAGTO_A_VISTA_ANS',
    'VL_PAGO_A_VISTA_ANS',
    'DT_INSCRICAO',
    'INSCRITO_DA',
    'ORIGEM_PAGAMENTO',
    'NR_COMPETENCIA_CARGA',
]
# Definição de variável geral para o registro da operadora específica (SC - 312924)
SC = 312924

# Filtragem dos dados para a operadora específica (registro 312924 - SC)
# Seleção das colunas de interesse
# Materializando o DataFrame com collect() - pois já filtramos e selecionamos as colunas, então o resultado deve ser mais leve para a memória
penalidades_sc = (
    lf_origem_penalidades_aplicadas_a_operadoras
    .filter(pl.col("REGISTRO_OPERADORA") == SC)
    .select(colunas_desejaveis)
    .collect()
)

In [4]:
# "CAST" ou conversão das colunas de data tipadas como "str" para o tipo "Date" do Polars, usando o formato específico de data presente nos dados ("%d/%m/%Y").
penalidades_sc = penalidades_sc.with_columns(pl.col(['DT_PUBLICACAO_1A_FINAL',
                                                    'DT_CIENCIA_RECONSIDERA_TOTAL',
                                                    'DT_SUSPENSAO_ADM',
                                                    'DT_SUSPENSAO_JUD',
                                                    'DT_VENC_GRU',
                                                    'DT_PAGTO_A_VISTA_ANS',
                                                    'DT_INSCRICAO',
                                                    'DT_ARQUIVAMENTO']).str.strptime(pl.Date, "%d/%m/%Y", exact=False, strict=False))

# Confirmando a conversão
penalidades_sc.show()

NR_DEMANDA,NR_PROCESSO,TIPO_PROCESSO,REGISTRO_OPERADORA,STATUS_DEMANDA,DT_PUBLICACAO_1A_FINAL,VL_MULTA_FIXA_1A,VL_TOTAL_APLICADO_1A,DT_CIENCIA_RECONSIDERA_TOTAL,TIPO_DECISAO_2A,VL_MULTA_FIXA_2A,VL_TOTAL_APLICADO_2A,VL_MULTA_FINAL_APLICADA,VL_TOTAL_DESCONTOS,DT_ARQUIVAMENTO,MOTIVO_ARQUIVAMENTO,TIPO_PENALIDADE,DT_SUSPENSAO_ADM,DT_SUSPENSAO_JUD,DT_VENC_GRU,VL_GRU,DE_SITUACAO_GRU,DT_PAGTO_A_VISTA_ANS,VL_PAGO_A_VISTA_ANS,DT_INSCRICAO,INSCRITO_DA,ORIGEM_PAGAMENTO,NR_COMPETENCIA_CARGA
i64,str,str,i64,str,date,i64,i64,date,str,i64,i64,i64,i64,date,str,str,date,date,date,i64,str,date,i64,date,str,str,i64
5379468,"""33910.004280/2022-35""","""Consumidor""",312924,"""Arquivado""",2023-06-25,88000,88000,null,null,0,0,88000,17600,2024-02-27,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2023-08-16,70400,"""Pago""",2023-08-16,70400,null,"""NAO""","""ANS""",202503
3419328,"""33903.003604/2017-40""","""Consumidor""",312924,"""Arquivado""",2017-05-23,66000,66000,null,"""Provimento Negado""",0,0,0,null,2020-09-24,"""Extinção do Processo (Artigo 5…","""Multa Pecuniária""",null,2019-03-15,2019-02-28,73240,"""Cancelada""",null,null,null,"""NAO""","""ANS""",202503
1664105,"""25785.014384/2012-31""","""Consumidor""",312924,"""Em Cobrança""",2015-08-11,72650,72650,null,"""Provimento Negado""",72650,72650,72650,null,null,null,"""Multa Pecuniária""",null,2017-05-17,2017-01-31,99916,"""Suspenso""",null,null,2017-04-03,"""SIM""","""DA""",202503
2580639,"""25782.009138/2015-30""","""Consumidor""",312924,"""Arquivado""",2016-11-03,66000,66000,null,"""Provimento Negado""",66000,66000,66000,null,2022-10-27,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2019-02-28,90625,"""Pago""",2020-10-06,99239,null,"""NAO""","""ANS""",202503
4431631,"""33910.026096/2019-41""","""Consumidor""",312924,"""Arquivado""",2022-04-06,79200,79200,null,null,0,0,79200,15840,2024-02-20,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2023-02-10,63360,"""Pago""",2023-02-10,63360,null,"""NAO""","""ANS""",202503

In [5]:
# Análise exploratória: total de multas pago a vista por ano de pagamento
consulta_valor_ano = penalidades_sc.group_by(pl.col("DT_PAGTO_A_VISTA_ANS")
                                             .dt
                                             .year()
                                             .alias("ANO_PAGTO")
                                             ).agg(pl.col("VL_PAGO_A_VISTA_ANS")
                                                                     .sum()
                                                                     .alias("TOTAL_ANO_PAGTO")
                                                                     ).sort("ANO_PAGTO")

consulta_valor_ano.show(14)

ANO_PAGTO,TOTAL_ANO_PAGTO
i32,i64
null,0
2013,126041
2014,170918
2015,185878
2016,711519
2017,995493
2018,4436404
2019,3991809
2020,1966389
2021,2372564
2022,1756637
2023,1848271
2024,2277453
2025,780976

# As informações geradas sugerem uma diminuição maior que 50% das multas pagas entre 2024 e 2025, é necessário investigar.

In [6]:
penalidades_sc.filter(pl.col("DT_PAGTO_A_VISTA_ANS").dt.year() >= 2024).sort("DT_PAGTO_A_VISTA_ANS").show(limit=None)

NR_DEMANDA,NR_PROCESSO,TIPO_PROCESSO,REGISTRO_OPERADORA,STATUS_DEMANDA,DT_PUBLICACAO_1A_FINAL,VL_MULTA_FIXA_1A,VL_TOTAL_APLICADO_1A,DT_CIENCIA_RECONSIDERA_TOTAL,TIPO_DECISAO_2A,VL_MULTA_FIXA_2A,VL_TOTAL_APLICADO_2A,VL_MULTA_FINAL_APLICADA,VL_TOTAL_DESCONTOS,DT_ARQUIVAMENTO,MOTIVO_ARQUIVAMENTO,TIPO_PENALIDADE,DT_SUSPENSAO_ADM,DT_SUSPENSAO_JUD,DT_VENC_GRU,VL_GRU,DE_SITUACAO_GRU,DT_PAGTO_A_VISTA_ANS,VL_PAGO_A_VISTA_ANS,DT_INSCRICAO,INSCRITO_DA,ORIGEM_PAGAMENTO,NR_COMPETENCIA_CARGA
i64,str,str,i64,str,date,i64,i64,date,str,i64,i64,i64,i64,date,str,str,date,date,date,i64,str,date,i64,date,str,str,i64
5729924,"""33910.010793/2023-66""","""Consumidor""",312924,"""Arquivado""",2023-09-18,33000,33000,null,null,0,0,33000,6600,2024-04-05,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-01-15,26400,"""Pago""",2024-01-11,26400,null,"""NAO""","""ANS""",202503
5707875,"""33910.006662/2023-84""","""Consumidor""",312924,"""Arquivado""",2023-09-05,66000,66000,null,null,0,0,66000,13200,2024-04-05,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-01-15,52800,"""Pago""",2024-01-11,52800,null,"""NAO""","""ANS""",202503
5764359,"""33910.013807/2023-01""","""Consumidor""",312924,"""Arquivado""",2023-11-09,30000,30000,null,null,0,0,30000,6000,2024-01-25,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-01-17,24000,"""Pago""",2024-01-16,24000,null,"""NAO""","""ANS""",202503
5751718,"""33910.011975/2023-54""","""Consumidor""",312924,"""Arquivado""",2023-09-14,80000,80000,null,null,0,0,80000,32000,2024-01-22,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-01-18,48000,"""Pago""",2024-01-16,48000,null,"""NAO""","""ANS""",202503
5185000,"""33910.032791/2021-66""","""Consumidor""",312924,"""Arquivado""",2023-08-24,60000,60000,null,null,0,0,60000,12000,2024-06-12,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-01-17,48000,"""Pago""",2024-01-17,48000,null,"""NAO""","""ANS""",202503
5428684,"""33910.021611/2022-00""","""Consumidor""",312924,"""Arquivado""",2023-05-15,79200,79200,null,"""Provimento Negado""",79200,79200,79200,null,2024-03-20,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-01-31,84736,"""Pago""",2024-01-31,84736,null,"""NAO""","""ANS""",202503
5579433,"""33910.033562/2022-40""","""Consumidor""",312924,"""Arquivado""",2023-12-28,60000,60000,null,null,0,0,60000,24000,2024-03-04,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-02-14,36000,"""Pago""",2024-02-09,36000,null,"""NAO""","""ANS""",202503
5896923,"""33910.036179/2023-24""","""Consumidor""",312924,"""Arquivado""",2024-01-11,30000,30000,null,null,0,0,30000,12000,2024-03-25,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-02-20,18000,"""Pago""",2024-02-20,18000,null,"""NAO""","""ANS""",202503
4986073,"""33910.006580/2021-78""","""Consumidor""",312924,"""Arquivado""",2023-12-06,88000,88000,null,null,0,0,88000,17600,2024-04-11,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-02-21,70400,"""Pago""",2024-02-20,70400,null,"""NAO""","""ANS""",202503
5266609,"""33910.035947/2021-61""","""Consumidor""",312924,"""Arquivado""",2023-09-04,60000,60000,null,null,0,0,60000,24000,2024-03-12,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-03-06,36000,"""Pago""",2024-03-04,36000,null,"""NAO""","""ANS""",202503
5502584,"""33910.025248/2022-93""","""Consumidor""",312924,"""Arquivado""",2024-01-11,66000,66000,null,null,0,0,66000,13200,2024-04-05,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-03-11,52800,"""Pago""",2024-03-04,52800,null,"""NAO""","""ANS""",202503
5577437,"""33910.033393/2022-48""","""Consumidor""",312924,"""Arquivado""",2024-01-04,88000,88000,null,null,0,0,88000,17600,2024-03-21,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-03-20,70400,"""Pago""",2024-03-14,70400,null,"""NAO""","""ANS""",202503
5185274,"""33910.031519/2021-69""","""Consumidor""",312924,"""Arquivado""",2024-01-11,88000,88000,null,null,0,0,88000,17600,2024-03-22,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-03-19,70400,"""Pago""",2024-03-14,70400,null,"""NAO""","""ANS""",202503
5946059,"""33910.004951/2024-20""","""Consumidor""",312924,"""Arquivado""",2024-03-07,60000,60000,null,null,0,0,60000,24000,2024-04-12,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-04-09,36000,"""Pago""",2024-04-03,36000,null,"""NAO""","""ANS""",202503
5563453,"""33910.032071/2022-81""","""Consumidor""",312924,"""Arquivado""",2024-04-02,60000,60000,null,null,0,0,60000,24000,2024-08-06,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-05-08,36000,"""Pago""",2024-05-06,36000,null,"""NAO""","""ANS""",202503
5405061,"""33910.012037/2022-91""","""Consumidor""",312924,"""Arquivado""",2024-03-28,88000,88000,null,null,0,0,88000,17600,2024-08-21,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-05-24,70400,"""Pago""",2024-05-16,70400,null,"""NAO""","""ANS""",202503
5157841,"""33910.027344/2021-95""","""Consumidor""",312924,"""Arquivado""",2022-01-11,88000,88000,null,"""Provimento Negado""",79200,79200,79200,null,2024-08-29,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-05-29,100616,"""Pago""",2024-05-29,100616,null,"""NAO""","""ANS""",202503
4662334,"""33910.013405/2020-56""","""Consumidor""",312924,"""Arquivado""",2021-11-18,275000,275000,null,"""Provimento Negado""",275000,275000,275000,null,2024-08-21,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-05-29,353458,"""Pago""",2024-05-29,353458,null,"""NAO""","""ANS""",202503
5432867,"""33910.014235/2022-99""","""Consumidor""",312924,"""Arquivado""",2023-04-04,33000,33000,null,"""Provimento Negado""",33000,33000,33000,null,2024-08-29,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-06-26,37085,"""Pago""",2024-06-26,37085,null,"""NAO""","""ANS""",202503
5723329,"""33910.009817/2023-34""","""Consumidor""",312924,"""Arquivado""",2024-05-27,79200,79200,null,null,0,0,79200,15840,2024-08-28,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-07-15,63360,"""Pago""",2024-07-05,63360,null,"""NAO""","""ANS""",202503
5737416,"""33910.038697/2022-00""","""Consumidor""",312924,"""Arquivado""",2024-04-23,59400,59400,null,null,0,0,59400,11880,2024-08-28,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-07-11,47520,"""Pago""",2024-07-05,47520,null,"""NAO""","""ANS""",202503
6028038,"""33910.018348/2021-82""","""Representação""",312924,"""Arquivado""",2024-06-03,25000,25000,null,null,0,0,25000,10000,2024-09-25,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-07-31,15000,"""Pago""",2024-07-30,15000,null,"""NAO""","""ANS""",202503
4886702,"""33910.008550/2021-04""","""Consumidor""",312924,"""Arquivado""",2021-08-17,66000,66000,null,"""Provimento Negado""",66000,66000,66000,null,2024-09-02,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-07-31,82401,"""Pago""",2024-07-30,82401,null,"""NAO""","""ANS""",202503
12371647,"""33910.026879/2021-49""","""Representação""",312924,"""Arquivado""",2024-06-18,70000,70000,null,null,0,0,70000,28000,2024-09-25,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-08-05,42000,"""Pago""",2024-08-05,42000,null,"""NAO""","""ANS""",202503
5431751,"""33910.014529/2022-11""","""Consumidor""",312924,"""Arquivado""",2024-07-13,30000,30000,null,null,0,0,30000,6000,2024-10-01,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-09-11,24000,"""Pago""",2024-08-16,24000,null,"""NAO""","""ANS""",202503
5773495,"""33910.015222/2023-18""","""Consumidor""",312924,"""Arquivado""",2024-06-26,60000,60000,null,null,0,0,60000,24000,2024-10-22,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-09-23,36000,"""Pago""",2024-09-23,36000,null,"""NAO""","""ANS""",202503
5067713,"""33910.017165/2021-40""","""Consumidor""",312924,"""Arquivado""",2022-08-07,88000,88000,null,"""Provimento Negado""",88000,88000,88000,null,2024-10-16,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-09-30,108557,"""Pago""",2024-09-30,108557,null,"""NAO""","""ANS""",202503
12171884,"""33910.029447/2023-51""","""Consumidor""",312924,"""Arquivado""",2024-07-31,80000,80000,null,null,0,0,80000,32000,2024-10-08,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-10-01,48000,"""Pago""",2024-10-01,48000,null,"""NAO""","""ANS""",202503
5448130,"""33910.022568/2022-91""","""Consumidor""",312924,"""Arquivado""",2024-08-10,66000,66000,null,null,0,0,66000,13200,2024-11-11,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-10-18,52800,"""Pago""",2024-10-17,52800,null,"""NAO""","""ANS""",202503
5531757,"""33910.026757/2022-33""","""Consumidor""",312924,"""Arquivado""",2024-08-29,88000,88000,null,null,0,0,88000,17600,2024-11-13,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-10-21,70400,"""Pago""",2024-10-17,70400,null,"""NAO""","""ANS""",202503
5452437,"""33910.023754/2022-48""","""Consumidor""",312924,"""Arquivado""",2024-08-07,79200,79200,null,null,0,0,79200,15840,2025-01-08,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-10-29,63360,"""Pago""",2024-10-28,63360,null,"""NAO""","""ANS""",202503
5650801,"""33910.043361/2022-51""","""Consumidor""",312924,"""Arquivado""",2024-08-16,79200,79200,null,null,0,0,79200,15840,2025-01-28,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-11-13,63360,"""Pago""",2024-11-13,63360,null,"""NAO""","""ANS""",202503
4415892,"""33910.026201/2019-41""","""Consumidor""",312924,"""Arquivado""",2024-10-01,88000,88000,null,null,0,0,88000,17600,2025-02-03,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-11-25,70400,"""Pago""",2024-11-22,70400,null,"""NAO""","""ANS""",202503
5633904,"""33910.014353/2022-05""","""Consumidor""",312924,"""Arquivado""",2024-10-09,50000,50000,null,null,0,0,50000,20000,2025-03-21,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-11-28,30000,"""Pago""",2024-11-27,30000,null,"""NAO""","""ANS""",202503
5613428,"""33910.040182/2022-61""","""Consumidor""",312924,"""Arquivado""",2024-10-22,30000,30000,null,null,0,0,30000,6000,2025-03-20,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-12-13,24000,"""Pago""",2024-12-13,24000,null,"""NAO""","""ANS""",202503
5680418,"""33910.002353/2023-35""","""Consumidor""",312924,"""Arquivado""",2024-10-25,88000,88000,null,null,0,0,88000,17600,2025-02-24,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-12-23,70400,"""Pago""",2024-12-20,70400,null,"""NAO""","""ANS""",202503
5540046,"""33910.029308/2022-47""","""Consumidor""",312924,"""Arquivado""",2024-10-25,88000,88000,null,null,0,0,88000,17600,2025-02-26,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-12-26,70400,"""Pago""",2024-12-23,70400,null,"""NAO""","""ANS""",202503
5634170,"""33910.041668/2022-17""","""Consumidor""",312924,"""Arquivado""",2024-10-21,30000,30000,null,null,0,0,30000,6000,2025-03-06,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2024-12-26,24000,"""Pago""",2024-12-23,24000,null,"""NAO""","""ANS""",202503
5677286,"""33910.002271/2023-91""","""Consumidor""",312924,"""Arquivado""",2024-10-24,33000,33000,null,null,0,0,33000,6600,2025-03-07,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2025-01-02,26400,"""Pago""",2025-01-02,26400,null,"""NAO""","""ANS""",202503
12630383,"""33910.030586/2024-17""","""Consumidor""",312924,"""Arquivado""",2024-12-02,80000,80000,null,null,0,0,80000,32000,2025-03-07,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2025-01-07,48000,"""Pago""",2025-01-07,48000,null,"""NAO""","""ANS""",202503
5071312,"""33910.039018/2022-10""","""Consumidor""",312924,"""Arquivado""",2023-12-05,88000,88000,null,"""Provimento Negado""",88000,88000,88000,null,2025-02-04,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2025-01-31,97161,"""Pago""",2025-01-28,97161,null,"""NAO""","""ANS""",202503
5878296,"""33910.004764/2023-65""","""Consumidor""",312924,"""Em Cobrança""",2024-12-10,88000,88000,null,null,0,0,88000,17600,null,null,"""Multa Pecuniária""",null,null,2025-02-06,70400,"""Pago""",2025-02-06,70400,null,"""NAO""","""ANS""",202503
5707598,"""33910.006641/2023-69""","""Consumidor""",312924,"""Arquivado""",2024-11-26,88000,88000,null,null,0,0,88000,17600,2025-03-31,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2025-02-10,70400,"""Pago""",2025-02-10,70400,null,"""NAO""","""ANS""",202503
6006200,"""33910.016592/2024-53""","""Consumidor""",312924,"""Em Cobrança""",2024-12-20,80000,80000,null,null,0,0,80000,32000,null,null,"""Multa Pecuniária""",null,null,2025-02-14,48000,"""Pago""",2025-02-12,48000,null,"""NAO""","""ANS""",202503
5724743,"""33910.009856/2023-31""","""Consumidor""",312924,"""Em Cobrança""",2024-12-26,88000,88000,null,null,0,0,88000,17600,null,null,"""Multa Pecuniária""",null,null,2025-02-18,70400,"""Pago""",2025-02-17,70400,null,"""NAO""","""ANS""",202503
12511889,"""33910.035060/2024-15""","""Consumidor""",312924,"""Arquivado""",2025-01-13,80000,80000,null,null,0,0,80000,32000,2025-03-26,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2025-02-21,48000,"""Pago""",2025-02-18,48000,null,"""NAO""","""ANS""",202503
5540768,"""33910.029500/2022-33""","""Consumidor""",312924,"""Arquivado""",2023-07-03,88000,88000,null,"""Provimento Negado""",88000,88000,88000,null,2025-03-14,"""Decisão condenatória com pagam…","""Multa Pecuniária""",null,null,2025-02-28,102230,"""Pago""",2025-02-26,102230,null,"""NAO""","""ANS""",202503
3028438,"""33903.012541/2016-31""","""Consumidor""",312924,"""Em Cobrança""",2017-06-27,66000,66000,null,"""Provimento Negado""",66000,66000,66000,null,null,null,"""Multa Pecuniária""",null,2020-10-14,2019-01-31,72356,"""Pago""",2025-02-28,127985,null,"""NAO""","""ANS""",202503
5746592,"""33910.011488/2023-91""","""Consumidor""",312924,"""Em Cobrança""",2023-09-28,30000,30000,null,null,0,0,30000,6000,null,null,"""Multa Pecuniária""",null,null,2025-03-11,24000,"""Pago""",2025-03-10,24000,null,"""NAO""","""ANS""",202503
5900255,"""33910.037162/2023-94""","""Consumidor""",312924,"""Em Cobrança""",2025-01-20,80000,80000,null,null,0,0,80000,32000,null,null,"""Multa Pecuniária""",null,null,2025-03-11,48000,"""Pago""",2025-03-10,48000,null,"""NAO""","""ANS""",202503

In [7]:
penalidades_sc.null_count()

shape: (1, 28)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ NR_DEMAND ┆ NR_PROCES ┆ TIPO_PROC ┆ REGISTRO_ ┆ … ┆ DT_INSCRI ┆ INSCRITO_ ┆ ORIGEM_PA ┆ NR_COMPE │
│ A         ┆ SO        ┆ ESSO      ┆ OPERADORA ┆   ┆ CAO       ┆ DA        ┆ GAMENTO   ┆ TENCIA_C │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ARGA     │
│ u32       ┆ u32       ┆ u32       ┆ u32       ┆   ┆ u32       ┆ u32       ┆ u32       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 0         ┆ 0         ┆ 0         ┆ 0         ┆ … ┆ 353       ┆ 0         ┆ 44        ┆ 0        │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# A última data de pagamento para o ano de 2025 foi registrada em 10/03/2025

1. Será necessário estimar os valores do ano de 2025 com base no primeiro bimestre do ano e anos anteriores;
2. Descartar Regressão Linear - o histórico de pagamento de multas de anos anteriores demonstra uma relação não linear entre eles;
3. Descartar Regressão Polinomial - a variação positiva e negativa geraria uma equação com muitas curvas, tornando o modelo desnecessariamente complexo;
4. Investigar correlação entre número de reclamações e valores de multa pagos.

In [ ]:
'''
1. select() - seleciona apenas as colunas relevantes para a análise de correlação;

2. drop_nulls() - elimina os valores nulos - há decisões de 1A que foram revistas, suspensas ou canceladas, resultando em valor nulo para as demais colunas;

3. filter() - filtra para as decisões tomadas após 2018 (antes disso os prazos entre 1A e PAGTO não eram homogêneos)

'''
visualiza_periodo_decisao_pagamento = penalidades_sc.select(pl.col(
                                            [
                                            'DT_PUBLICACAO_1A_FINAL',
                                            'DT_PAGTO_A_VISTA_ANS',
                                            'VL_PAGO_A_VISTA_ANS'
                                            ])
                                            ).drop_nulls(
                                                ).filter(
                                                    (pl.col('DT_PUBLICACAO_1A_FINAL') > date(2018,1,1))
                                                    ).sort('DT_PUBLICACAO_1A_FINAL', 
                                                       descending=True
                                                       ).show(
                                                            limit=None, 
                                                            decimal_separator=',', 
                                                            thousands_separator='.',
                                                            )

DT_PUBLICACAO_1A_FINAL,DT_PAGTO_A_VISTA_ANS,VL_PAGO_A_VISTA_ANS
date,date,i64
2025-01-20,2025-03-10,48.000
2025-01-13,2025-02-18,48.000
2024-12-26,2025-02-17,70.400
2024-12-20,2025-02-12,48.000
2024-12-10,2025-02-06,70.400
2024-12-02,2025-01-07,48.000
2024-11-26,2025-02-10,70.400
2024-10-25,2024-12-23,70.400
2024-10-25,2024-12-20,70.400
2024-10-24,2025-01-02,26.400
2024-10-22,2024-12-13,24.000
2024-10-21,2024-12-23,24.000
2024-10-09,2024-11-27,30.000
2024-10-01,2024-11-22,70.400
2024-08-29,2024-10-17,70.400
2024-08-16,2024-11-13,63.360
2024-08-10,2024-10-17,52.800
2024-08-07,2024-10-28,63.360
2024-07-31,2024-10-01,48.000
2024-07-13,2024-08-16,24.000
2024-06-26,2024-09-23,36.000
2024-06-18,2024-08-05,42.000
2024-06-03,2024-07-30,15.000
2024-05-27,2024-07-05,63.360
2024-04-23,2024-07-05,47.520
2024-04-02,2024-05-06,36.000
2024-03-28,2024-05-16,70.400
2024-03-07,2024-04-03,36.000
2024-01-11,2024-02-20,18.000
2024-01-11,2024-03-04,52.800
2024-01-11,2024-03-14,70.400
2024-01-04,2024-03-14,70.400
2023-12-28,2024-02-09,36.000
2023-12-06,2024-02-20,70.400
2023-12-05,2025-01-28,97.161
2023-11-09,2024-01-16,24.000
2023-11-03,2023-12-15,48.000
2023-09-28,2025-03-10,24.000
2023-09-18,2024-01-11,26.400
2023-09-14,2023-10-24,48.000
2023-09-14,2024-01-16,48.000
2023-09-05,2024-01-11,52.800
2023-09-05,2023-10-11,48.000
2023-09-04,2024-03-04,36.000
2023-09-01,2023-10-04,36.000
2023-08-31,2023-10-04,36.000
2023-08-30,2023-10-11,48.000
2023-08-24,2024-01-17,48.000
2023-07-31,2023-10-04,70.400
2023-07-28,2023-09-01,48.000